version: '3'

services: 
  app:
    build: 
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js docker-entrypoint.sh
    networks:     
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on: 
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true    
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network
      
  web:
    build: 
      context: nginx
    container_name: web
    volumes:
      - ./nginx:/usr/share/nginx
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    networks: 
      - node-network              

networks: 
  node-network:
    driver: bridge